services:
  app:
    build:
      context: .
      args:
        - DEV=true
    env_file:
      - .env.sample
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - database
  database:
    image: mariadb:10.6
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    volumes:
      - "mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=recipe
      - MARIADB_DATABASE=recipe

volumes:
  mariadb: