# Generated by Django 4.2.16 on 2024-10-28 15:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="tz",
            field=timezone_field.fields.TimeZoneField(
                blank=True,
                choices_display="WITH_GMT_OFFSET",
                help_text="In which timezone should dates and times be displayed",
                max_length=32,
                null=True,
                verbose_name="time zone",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.client",
                verbose_name="client",
            ),
        ),
    ]
